### ISSUE TITLE
Question about determining transmission of the current frame is finished

### ISSUE THREAD

**Issue by TronYY** [Shawnxm/EMP#1]
Dear sir,  you mentioned

> (2) 𝐶2 of one vehicle has not arrived (e.g., due to limited bandwidth) but the 𝐶3 of all its neighboring vehicles have been delivered; (3) Neither 𝐶1 nor 𝐶2 of one vehicle has arrived but its neighbors finish uploading their 𝐶3s and 𝐶4s.

Why the C2 of a vehicle can be replaced by C3 of all its neighbor vehicle? (also, C1 C2 replaced by neighbors' C3 C4).  We can't guarantee a vehicle's and neighbors‘ three boundaries (Lover, Lorigin,Lunder) are very likely in the similar positions， right？

I am confused about this.

**Comment by Shawnxm** [comment]
This is determined by the principles of the Voronoi/Power diagram. In the design, we use the vehicle positions to construct Voronoi/Power diagrams with different weights (please see Figure 7/8 in the [paper](https://dl.acm.org/doi/abs/10.1145/3447993.3483242)), so we say the C1 (or C2) of a vehicle can roughly be replaced by all C4s (or C3s) of its neighboring vehicles.

**Comment by TronYY** [comment]
I understand. Thank you. Solid work！

How long did it take you to finish this work?

(you can close this issue)
