### ISSUE TITLE
Some of the .txt files are missing

### ISSUE THREAD

**Issue by stonegen** [Shawnxm/EMP#4]
When I tried to run the vehicle, I got an error that the "0000001.txt" file was not found. I could not find this file in the repo. Where to find all the files required by different vehicles and how to configure the **data path** as highlighted in the following command.

java -Djava.library.path=build/src/main/cpp \
   -Dlog4j.configurationFile=src/main/resources/log4j2-config.xml \
   -cp build/libs/emp-1.0.jar org.emp.vehicle.[vehicle type] \
   -i [server ip] -p [server port] -c [client port] \
   -v [vehicle ID] -d [**data path**] -r [frame rate]

The following screenshot shows the mentioned behavior. Please note that as I couldn't find the file path, I set up a dummy data path.
![796F103A-FE42-411D-A5B1-CFC3AB9738DE](https://user-images.githubusercontent.com/46588833/186886078-5dfacd96-5bb3-4cf3-bbce-5f7684aebe8b.jpeg)

**Comment by ThankPan** [comment]
I'm also curious about where to get the dataset to reproduce your work. Do I need to generate all those data from scratch using DeepGTAV - PreSIL? Or could I use pre-generated dataset provided by them here[https://uwaterloo.ca/waterloo-intelligent-systems-engineering-lab/projects/precise-synthetic-image-and-lidar-presil-dataset-autonomous](url).

**Comment by Shawnxm** [comment]
Hi guys, I will email you the link to access the example data shortly.

@stonegen "0000001.txt" is just an auxiliary file used to indicate which frame ID a vehicle has (assuming some vehicles may not be generating sensor data continuously).

@ThankPan You can use the data collection tool [DeepGTAV-PreSIL](https://github.com/Shawnxm/DeepGTAV-PreSIL/tree/modified_for_emp) mentioned in the [README](https://github.com/Shawnxm/EMP/blob/master/README.md) to collect more data in the game.
